### ISSUE TITLE
Suggestions on how to improve the workshop instructions

### ISSUE THREAD

**Issue by paragao** [aws-samples/aws-hpc-tutorials#105]
a. When recommending customers to create an EC2 Key Pair, the instructions say that customers should "chmod 600 <key_pair>" but AWS official documentation states that it should be "chmod 400 <key_pair>". In order to avoid confusion, I suggest the text to be changed accordingly to the official EC2 documentation. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

b. When creating the cluster (module IV, step b) add additional text explaining what is the cluster name and that it uses the "cluster default" section of the config file. It it is misleading how AWS ParallelCluster is creating the cluster since the fsx section is name myfsx and the cluster name used is my-fsx-cluster. Customers might get the idea that they are somehow related and create confusion.

c. On the same module IV, step b, should update the config file to add a separate compute queue similar to what was done in module III, step c.

**Comment by mhuguesaws** [comment]
Thank you for your feedback. It will be taken into account a new version of the workshop that's coming up before end of 2021.
