### ISSUE TITLE
AWS pcluster 3.0

### ISSUE THREAD

**Issue by MAlberts99** [aws-samples/aws-hpc-tutorials#117]
Hi all,
with the release of pcluster 3.0 the guide has become outdated. For version 2 I found this guide tremendously helpful and it would be great if it could be updated to version 3.0 as well.

Thank you for your work on it :)

**Comment by sean-smith** [comment]
@pokulo We'll update the pip install to install the latest 2.X version. For pcluster 3.0, updates will come in the future. 

For now just use the following install command:
```
pip install "aws-parallelcluster<3.0" -U --user
```

**Comment by sean-smith** [comment]
@pokulo workshop updated to PC 3.X
