### ISSUE TITLE
github.com/hpc/ior branch problem

### ISSUE THREAD

**Issue by quiver** [aws-samples/aws-hpc-tutorials#25]
On the following page, you're supposed to check out `io500-sc19` branch of https://github.com/hpc/ior.
But that branch does not exist anymore.

```
$ git clone https://github.com/hpc/ior.git
$ cd ior
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/hpc/ior.git
  Push  URL: https://github.com/hpc/ior.git
  HEAD branch: master
  Remote branches:
    3.2                    tracked
    feature-mdtest-cleanup tracked
    fix-189                tracked
    fix-mem                tracked
    fix-modules            tracked
    master                 tracked
    rc                     tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

Please update the doc accordingly.

Cheerts.

**Comment by sean-smith** [comment]
Thanks @quiver

**Comment by sean-smith** [comment]
@quiver I took a look and `io500-sc19` is a tag so `git checkout io500-sc19` works for me. Does it not work for you?

We can update this to `3.2` branch

**Comment by quiver** [comment]
@sean-smith 
> @quiver I took a look and io500-sc19 is a tag so git checkout io500-sc19 works for me. Does it not work for you?

Sorry, it's my fault.
I thought it's the name of the branch.

No need to change the documentation, so I'll  close this issue.

P.S. I forgot to mention the URL in question.
https://www.hpcworkshops.com/04-amazon-fsx-for-lustre/04-install-ior.html

I really enjoy this tutorial.

Cheers.
