### ISSUE TITLE
Format for Distributed Learning subsections headers

### ISSUE THREAD

**Issue by perifaws** [aws-samples/aws-hpc-tutorials#28]
The subsection headers have a different format for the distributed ML subsections  differs from others. Change is required to keep consistency.

![image](https://user-images.githubusercontent.com/62559210/94043704-e0fdbf80-fd92-11ea-91f2-89a231903636.png)

![image](https://user-images.githubusercontent.com/62559210/94043723-e6f3a080-fd92-11ea-81d0-2f7dfd85f2da.png)

**Comment by sean-smith** [comment]
Resolved in #29
