### ISSUE TITLE
hpc workshop distributed ML multiple errors

### ISSUE THREAD

**Issue by charlescurt** [aws-samples/aws-hpc-tutorials#283]
I am working through this workshop https://www.hpcworkshops.com/09-ml-on-parallelcluster.html, and all has been going well until the final part for distributed ML.

1. There is a typo and outdated instance in "b. Create a distributed ML cluster"
```
     Dcv:
        Emabled: true
```
_p3dn.24xlarge_ no longer exists as an available instance type.

2. After fixing these errors, I get new errors for a "S3BucketUriValidator error" for permissions to my s3 bucket, which I cannot get past in the manager UI no amount of permission adding helps.

3. I can however deploy this through the command :
`pcluster create-cluster --cluster-name ml-cluster -c ml-config.yaml`
When deployed and try to run the preprocess step I then end up with this new issue:
```
srun --exclusive -n 1 preprocess.sh
srun: Force Terminated job 1
srun: error: Node failure on compute-dy-p4d24xlarge-1
srun: error: Job allocation 1 has been revoked
```

Please let me know if there is more updated documentation around this, as I am very interested in distributed ML on the platform.

**Comment by sean-smith** [comment]
Hi Charles, we're actively working on this and know the distributed training workshop is dated. 

See https://ml.hpcworkshops.com/
