### ISSUE TITLE
Incorrect region specified for the console

### ISSUE THREAD

**Issue by jefffor** [aws-samples/aws-hpc-tutorials#364]
The CFT is correct and reopens in the right region but would be less confusing to start in Ohio instead of Northern Virginia

[Current page](https://weather.hpcworkshops.com/01-aws-getting-started/02-aws-console-login.html)

Start this workshop by selecting an AWS Region:

Choose the Region drop-down menu, then choose **US East (N. Virginia) us-east-1.**

Would be better as Ohio

**Comment by sean-smith** [comment]
Resolved in #365 and #366
