### ISSUE TITLE
Multiple workshop edits - user experience in CLI instructions and new feature in Parallel Cluster Manager

### ISSUE THREAD

**Issue by natalie-white-aws** [aws-samples/aws-hpc-tutorials#367]
the last 2 screenshots [on this page](https://www.hpcworkshops.com/03-deploy-pcm/01-deploy-pcm.html) are swapped - it should show the Capabilities acknowledgements in step 2, and the CloudFormation pcluster-manager screenshot should be in step 4.

**Comment by natalie-white-aws** [comment]
also, [on this page ](https://www.hpcworkshops.com/04-pcluster-cli/05-logon-pc.html) “.pem” needs to be added to the end of “lab-your-key” in the pcluster ssh command

**Comment by natalie-white-aws** [comment]
There’s a new section in the Parallel Cluster Manager UI that includes a shared storage configuration -  please add it to the instructions [on this page](https://www.hpcworkshops.com/05-create-cluster/01-create-cluster.html)

**Comment by natalie-white-aws** [comment]
Creating clusters via the Parallel Cluster Manager fails in EE accounts with the error, for the simple case and for the high-performance FSx case. This is a blocking issue for the workshop.

`Resource handler returned message: "User with accountId: [redacted]  is not authorized to perform CreateLogGroup with Tags. An additional permission "logs:TagResource" is required. (Service: CloudWatchLogs, Status Code: 400, Request ID: [redacted])" (RequestToken: [redacted], HandlerErrorCode: GeneralServiceException)`

**Comment by sean-smith** [comment]
Thanks @natalie-white-aws 

1. https://github.com/aws-samples/aws-hpc-tutorials/pull/368
2. https://github.com/aws-samples/aws-hpc-tutorials/pull/369
3. Storage - this needs lots of changes, we're going to skip this update for now
4. https://github.com/aws-samples/aws-hpc-tutorials/pull/370

**Comment by sean-smith** [comment]
The big one is the link in the workshop #370 is wrong and needs to be updated. Please see https://pcluster.cloud for the current one.
