### ISSUE TITLE
Manual install of WRF failing, missing wrong library (solved, just FYI)

### ISSUE THREAD

**Issue by fs-jbzambon** [aws-samples/aws-hpc-tutorials#452]
Hello again! I'm trying to complete the (Optional) WRF Manual Install in the AWS HPC for Numerical Weather Prediction (NWP) Workshop. I am able to get through to the final compile step, which fails with a missing HDF5 fortran library.

`ld: cannot find -lhdf5hl_fortran`

This is found in the final stage of the compile, where it attempts to build wrf.exe

```
time mpif90 -f90=ifort -o wrf.exe -qopenmp -fpp -auto -O3 -ip -fp-model precise -w -ftz -align all -fno-alias -FR -convert big_endian   -ip   wrf.o ../main/module_wrf_top.o libwrflib.a /fsx/WRF-4.3.3/external/fftpack/fftpack5/libfftpack.a /fsx/WRF-4.3.3/external/io_grib1/libio_grib1.a /fsx/WRF-4.3.3/external/io_grib_share/libio_grib_share.a /fsx/WRF-4.3.3/external/io_int/libwrfio_int.a -L/fsx/WRF-4.3.3/external/esmf_time_f90 -lesmf_time /fsx/WRF-4.3.3/external/RSL_LITE/librsl_lite.a /fsx/WRF-4.3.3/frame/module_internal_header_util.o /fsx/WRF-4.3.3/frame/pack_utils.o -L/fsx/WRF-4.3.3/external/io_netcdf -lwrfio_nf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/._view/tlhma2rztm3gqnxczsy3exciogteocn5/lib -lnetcdff -lnetcdf  -L/fsx/WRF-4.3.3/external/io_pnetcdf -lwrfio_pnf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lpnetcdf   -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lm -lz    -L/fsx/spack/opt/spack/linux-amzn2-zen/intel-2021.5.0/netcdf-fortran-4.6.0-5qwtuzjet5cikyrfktusokbtbxfoqfac/lib -lhdf5_hl -lhdf5 -lz   
ld: cannot find -lhdf5hl_fortran
```

This issue is because WRF is incorrectly searching for `lhdf5hl_fortran` instead of `lhdf5_hl_fortran`

So after configure but before compile you need to vi into configure.wrf and swap any instance of `lhdf5hl_fortran` with `lhdf5_hl_fortran` (e.g. only found in LIB_EXTERNAL)

```
$ diff configure.wrf configure.wrf_broken 
122c122
<                       -L$(WRF_SRC_ROOT_DIR)/external/io_netcdf -lwrfio_nf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/._view/tlhma2rztm3gqnxczsy3exciogteocn5/lib -lnetcdff -lnetcdf  -L$(WRF_SRC_ROOT_DIR)/external/io_pnetcdf -lwrfio_pnf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lpnetcdf   -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lhdf5_hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lm -lz
---
>                       -L$(WRF_SRC_ROOT_DIR)/external/io_netcdf -lwrfio_nf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/._view/tlhma2rztm3gqnxczsy3exciogteocn5/lib -lnetcdff -lnetcdf  -L$(WRF_SRC_ROOT_DIR)/external/io_pnetcdf -lwrfio_pnf -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lpnetcdf   -L/fsx/spack/var/spack/environments/wrf_build/.spack-env/view//lib -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lm -lz
```

Hope this helps someone, thanks!

-Joe

**Comment by mhuguesaws** [comment]
The weather workshops on github is archived. Did you consult the new workshop https://catalog.workshops.aws/nwp-on-aws/en-US/2-wrf/a-install-wrf?

**Comment by fs-jbzambon** [comment]
Yessir, that is the workshop I was using. Specifically, [this page](https://catalog.workshops.aws/nwp-on-aws/en-US/2-wrf/e-manual-install-wrf). I don't know if its just WRFv.4.3.3 but the compile fails on the `./compile -j 4 em_real 2>&1 | tee compile.log` step for the above reason. Thanks!

**Comment by t-brown** [comment]
It's in all version of WRF, specifically line 735 of [Config.pl](https://github.com/wrf-model/WRF/blob/21c72141142fc6c8d203d2bf79f1990e45a0aef8/arch/Config.pl#L735C62-L735C77).

According to the HDF5 [documentation](https://github.com/HDFGroup/hdf5/blob/59a0d8baef9e0a5acbe57cb8c0a80b5c42251b51/release_docs/HISTORY-1_10_0-1_12_0.txt#L656), there should be symbolic links in place:
```

    - Added symbolic links libhdf5_hl_fortran.so to libhdf5hl_fortran.so and
      libhdf5_hl_fortran.a to libhdf5hl_fortran.a in hdf5/lib directory for
      autotools installs.  These were added to match the name of the files
      installed by cmake and the general pattern of hl lib files.  We will
      change the names of the installed lib files to the matching name in
      the next major release.

      (LRK - 2019/01/04, HDFFV-10596)
```
Yet they are clearly not there. You might end up going down a rabbit hole figuring out why the symbolic links aren't there and what the fix is. Maybe ping @brtnfld ?

**Comment by t-brown** [comment]
Also note the comment in the Spack [package](https://github.com/spack/spack/blob/ae08b25dacd56b287d8c80ad648b998cfa2ec8cb/var/spack/repos/builtin/packages/hdf5/package.py#L437). So maybe ping @kkeene44 to see if the WRF package could put in a test for which version of the high level library is installed?
