### ISSUE TITLE
source for architecture diagram

### ISSUE THREAD

**Issue by mrgum** [aws-samples/aws-hpc-tutorials#457]
Is the source for ./static/images/hpc-aws-parallelcluster-workshop/pc-architecture.png available? looks like draw.io?

It would be a handy parallel cluster resource

**Comment by sean-smith** [comment]
It's a pptx file:
[pcluster-architecture.pptx](https://github.com/aws-samples/aws-hpc-tutorials/files/13602836/pcluster-architecture.pptx)

**Comment by mrgum** [comment]
thank you
